# Generated by Django 6.1 on 2026-08-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default='2026-08-11'),
            preserve_default=False,
        ),
    ]
