# Generated by Django 6.1 on 2026-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='date_posted',
            new_name='post_date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='slug',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
