# Generated by Django 6.1 on 2026-08-18 09:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobs_is_active_jobs_slug_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Applications',
        ),
    ]
